version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:7.2
    container_name: app-v1
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    networks:
      - app-network
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

  webserver:
    image: nginx:alpine
    container_name: webserver-v1
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  db:
    image: mariadb:10.3
    container_name: db-v1
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wizzer
      MYSQL_ROOT_PASSWORD: ahte46AJRT*
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network
    volumes:
      - dbdata:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
